version: '3'
services:
  portfolio:
    build:
      context: . # Asegúrate de que el contexto esté configurado correctamente
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules/
    working_dir: /app
    stdin_open: true
    tty: true
    restart: always